### ISSUE TITLE
buildevents: command not found

### ISSUE THREAD

**Issue by mmpashby** [honeycombio/buildevents-orb#24]
We have a failing job at the with_job_span step that produces an error like so:

```
#!/bin/bash -eo pipefail
# choose the right buildevents binary
if uname -a | grep Linux | grep x86_64 > /dev/null 2>&1 ; then
  export PATH=$PATH:/tmp/buildevents/be/bin-linux:/tmp/be/bin-linux
elif uname -a | grep Darwin > /dev/null 2>&1; then
  export PATH=$PATH:/tmp/buildevents/be/bin-darwin:/tmp/be/bin-darwin
fi

# if there are any extra context values, add them
if [ -e /tmp/buildevents/extra_fields.lgfmt ] ; then
  export BUILDEVENT_FILE=/tmp/buildevents/extra_fields.lgfmt
fi

# go ahead and report the span
buildevents step $CIRCLE_WORKFLOW_ID \
  $(cat /tmp/buildevents/be/${CIRCLE_JOB}-${CIRCLE_NODE_INDEX}/span_id) \
  $(cat /tmp/buildevents/be/${CIRCLE_JOB}-${CIRCLE_NODE_INDEX}/start) \
  ${CIRCLE_JOB}

/bin/bash: line 13: buildevents: command not found

Exited with code exit status 127
```
The environment setup looks like this:

```
Build-agent version 1.0.54207-5704a5fc (2021-03-16T17:42:41+0000)
System information:
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: xfs
 Cgroup Driver: cgroupfs
 Kernel Version: 4.15.0-1092-aws
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
```

**Comment by vreynolds** [comment]
Have you added a `buildevents/start_trace` at the beginning of the workflow? That's the step that installs the buildevents executable. You can see it used here in the `setup` job: https://github.com/honeycombio/buildevents/blob/main/.circleci/config.yml

**Comment by mmpashby** [comment]
hey @vreynolds - yes, we do. Like so:

```
# Start HoneyComb buildevents trace
start_honeycomb_trace: &start_honeycomb_trace
    executor: linuxgo
    steps:
      - buildevents/start_trace

# HoneyComb buildevents trace watches for job to finish then ends trace
honeycomb_trace_watch: &honeycomb_trace_watch
    executor: linuxgo
    steps:
      - buildevents/watch_build_and_finish
```
