### ISSUE TITLE
Pipeline parameters unavailable within a span

### ISSUE THREAD

**Issue by rkennedy-mode** [honeycombio/buildevents-orb#26]
Something in `buildevents/with_job_span` appears to obscure CircleCI pipeline variables. Using the following CircleCI configuration:

```yaml
version: 2.1

parameters:
  base_docker_image:
    description: "Name of the base docker image to use"
    type: "string"
    default: "cimg/base:2021.04"
  trunk_branch_name:
    description: "Name of the trunk branch"
    type: "string"
    default: "trunk"

orbs:
  buildevents: honeycombio/buildevents@0.2.8

workflows:
  build:
    jobs:
      - setup-buildevents
      - watch-buildevents:
          requires: [ "setup-buildevents" ]
      - test:
          requires: [ "setup-buildevents" ]

executors:
  common:
    docker:
      - image: << pipeline.parameters.base_docker_image >>

commands:
  command-using-pipeline-parameter:
    description: This command uses a pipeline parameter.
    steps:
      - run: echo "The trunk branch is named '<< pipeline.parameters.trunk_branch_name >>'"

jobs:
  setup-buildevents:
    executor: common
    steps:
      - buildevents/start_trace

  watch-buildevents:
    executor: common
    steps:
      - buildevents/watch_build_and_finish:
          timeout: 60

  test:
    executor: common
    steps:
      - buildevents/with_job_span:
          steps:
            - command-using-pipeline-parameter
            - run: echo "I'm test"
```

Running the `circleci` CLI config validation indicates that the pipeline parameter `trunk_branch_name` can not be found:

```
% circleci config validate
Error: Error calling workflow: 'build'
Error calling job: 'test'
Error calling command: 'buildevents/with_job_span'
Error calling command: 'command-using-pipeline-parameter'
Unknown variable(s): trunk_branch_name
```

This error can also be seen if the config is merged and CircleCI allowed to attempt building it:

![image](https://user-images.githubusercontent.com/47543687/123703937-e99b8e80-d819-11eb-9c12-65ed22f97777.png)

If the invocation of the `test` job removes the call to `buildevents/with_job_span` then things begin working again. e.g.

```yaml
  test:
    executor: common
    steps:
      - command-using-pipeline-parameter
      - run: echo "I'm test"
```

**Comment by vreynolds** [comment]
It looks like pipeline parameters are intentionally excluded from orbs' scope: https://circleci.com/docs/2.0/pipeline-variables/#the-scope-of-pipeline-parameters

You will need to pass it through as a command parameter:

```yaml
commands:
  command-using-pipeline-parameter:
    description: This command uses a pipeline parameter.
    parameters:
      trunk_branch_name:
        type: string
    steps:
      - run: echo "The trunk branch is named '<< parameters.trunk_branch_name >>'"
```

```yaml
test:
  executor: common
  steps:
    - buildevents/with_job_span:
        steps:
          - command-using-pipeline-parameter:
              trunk_branch_name: << pipeline.parameters.trunk_branch_name >>
          - run: echo "I'm test"
```
